# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Irrlicht 3D plot
#' @description
#' Creates a 3D plot using the Irrlicht engine.
#' 
#' @param points_df optional - data.frame with coordinates and attributes 
#' of scattered points 
#' @param mesh_string_input floet
#' @param video_driver
#' \itemize{
#'   \item{"a": }{OPENGL (default)} 
#'   \item{"b": }{DIRECT3D9}
#'   \item{"c": }{DIRECT3D8}
#'   \item{"d": }{BURNINGSVIDEO}
#'   \item{"e": }{SOFTWARE}
#'   \item{"f": }{NULL}
#' }
#'
#' @return boolean value - side effect; irrlicht window is relevant
#'
#' @examples
#' \dontrun{
#' plot_irr(
#'   points = data.frame(
#'     x = rnorm(500)*200, 
#'     y = rnorm(500)*200, 
#'     z = rnorm(500)*200,
#'     size = rnorm(500)*10 
#'   )
#' )
#' }
#'
#' @export
plot_irr <- function(points_df = NULL, mesh_string_input = NULL, video_driver = 'a') {
    .Call('Rirrlicht_plot_irr', PACKAGE = 'Rirrlicht', points_df, mesh_string_input, video_driver)
}

