# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' position
#' 
#' @description
#' huhu
#'  
#' @param corner_points huhu
#' 
#' @export
position_calc <- function(corner_points) {
    .Call('Rirrlicht_position_calc', PACKAGE = 'Rirrlicht', corner_points)
}

#' normal
#' 
#' @description
#' huhu
#'  
#' @param corner_points huhu
#' 
#' @export
normal_calc <- function(corner_points) {
    .Call('Rirrlicht_normal_calc', PACKAGE = 'Rirrlicht', corner_points)
}

#' Irrlicht 3D plot
#' @description
#' Creates a 3D plot using the Irrlicht engine.
#' 
#' @param points_df optional - data.frame with coordinates and attributes 
#' of scattered points 
#' @param raster_paths_cv troooeeeet
#' @param raster_corners_df huuuup
#' @param mesh_cv floet
#' @param doomhud fluet
#' @param video_driver
#' \itemize{
#'   \item{"a": }{OPENGL (default)} 
#'   \item{"b": }{DIRECT3D9}
#'   \item{"c": }{DIRECT3D8}
#'   \item{"d": }{BURNINGSVIDEO}
#'   \item{"e": }{SOFTWARE}
#'   \item{"f": }{NULL}
#' }
#'
#' @return boolean value - side effect; irrlicht window is relevant
#'
#' @examples
#' \dontrun{
#' plot_irr(
#'   points = data.frame(
#'     x = rnorm(500)*200, 
#'     y = rnorm(500)*200, 
#'     z = rnorm(500)*200,
#'     size = rnorm(500)*10 
#'   ),
#'   raster_paths_cv = c("data-raw/berries.png")
#' )
#' }
#'
#' @export
plot_irr <- function(points_df = NULL, raster_paths_cv = NULL, raster_corners_df = NULL, mesh_cv = NULL, doomhud = FALSE, video_driver = 'a') {
    .Call('Rirrlicht_plot_irr', PACKAGE = 'Rirrlicht', points_df, raster_paths_cv, raster_corners_df, mesh_cv, doomhud, video_driver)
}

