# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' test
#'
#' @description
#' test
#'
#' @param test
#'
#' @return test
#'
#' @examples
#' 1+1
#'
#' @export
testirr1 <- function() {
    .Call('Rirrlicht_testirr1', PACKAGE = 'Rirrlicht')
}

